local fx = require'functions'
local NS = { noremap = true, silent = true }
local function map(mode, key, action, settings)
    vim.api.nvim_set_keymap(mode, key, action, settings or NS)
end

map('n', '<Space>',   '<Leader>')
map('n', '<Leader>d', '"_d')
map('n', '<Leader>c', '"_c')
map('n', '<Leader>D', '"_D')
map('n', '<Leader>C', '"_C')
map('x', '<Leader>d', '"_d')
map('x', '<Leader>c', '"_c')
map('n', '<Leader>o', 'o<Esc>')
map('n', '<Leader>O', 'O<Esc>')
map('i', '<C-BS>',    '<C-W>')
map('i', '<C-Down>',  '<Esc>}zzi')
map('i', '<C-Up>',    '<Esc>{zzi')
map('i', '<S-Down>',  '<Esc>}zzi')
map('i', '<S-Up>',    '<Esc>{zzi')
map('x', '<C-Down>',  '}zz')
map('x', '<C-Up>',    '{zz')
map('x', '<S-Down>',  '}zz')
map('x', '<S-Up>',    '{zz')
map('n', '<C-Down>',  '}zz')
map('n', '<C-Up>',    '{zz')
map('n', '<S-Down>',  '}zz')
map('n', '<S-Up>',    '{zz')
map('n', 'zp',        'vipzf')
map('n', 'yil',       'my^Y`y')
map('n', '<Esc>',     '<cmd>noh<CR>')
map('n', '<Leader>s', '<cmd>w<CR>')
map("n", "bd",        '<cmd>bd<CR>')

vim.keymap.set('n', 'K',        fx.show_documentation, NS)
vim.keymap.set('n', '<C-H>',    fx.end_create_line,   NS)
vim.keymap.set('n', '<C-Down>', fx.end_create_line,   NS)
